# Generated by Django 3.2 on 2021-04-25 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(default='movie_default.jpg', upload_to='movie_posters')),
                ('trailer_url', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('production', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(default='people_default.jpg', upload_to='people_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(default='show_default.jpg', upload_to='show_posters')),
                ('trailer_url', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=100)),
                ('premier_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('network', models.CharField(max_length=100)),
            ],
        ),
    ]
