# Generated by Django 3.2 on 2021-04-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='directors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='age',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default_poster.png', upload_to='movie_posters'),
        ),
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(default='default_poster.png', upload_to='show_posters'),
        ),
    ]
