# Generated by Django 3.2 on 2021-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0002_auto_20210427_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default_poster.jpg', upload_to='movie_posters'),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(default='default_poster.jpg', upload_to='show_posters'),
        ),
    ]
