# Generated by Django 3.2 on 2021-05-04 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmdb', '0005_auto_20210504_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='producer',
            new_name='producers',
        ),
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='premier_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.movie')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.show')),
            ],
        ),
    ]
