# Generated by Django 3.2 on 2021-05-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0006_auto_20210504_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='show',
            name='producers',
            field=models.CharField(max_length=250),
        ),
    ]
