# Generated by Django 3.2 on 2021-05-04 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0007_auto_20210504_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='premier_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
